# Generated by Django 5.2.5 on 2025-08-23 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.class')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.class')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='Question', null=True)),
                ('max_mark', models.PositiveIntegerField(default=10)),
                ('model_answer', models.TextField(help_text='The standard correct answer text.')),
                ('marking_scheme', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test')),
            ],
            options={
                'ordering': ['q_number'],
                'unique_together': {('test', 'q_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='student_answers/')),
                ('ocr_text', models.TextField(blank=True, help_text='AI recognized text from handwriting.', null=True)),
                ('mark_gained', models.FloatField(default=0)),
                ('ai_evaluation_summary', models.TextField(blank=True, help_text='AI comparison summary.', null=True)),
                ('ai_strength_points', models.TextField(blank=True, null=True)),
                ('ai_improvement_points', models.TextField(blank=True, null=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('question', 'student')},
            },
        ),
    ]
