# Generated by Django 5.2.5 on 2025-08-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('pdf_file', models.FileField(upload_to='marking_principles/')),
                ('extracted_text', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='marking_principle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.markingprinciple'),
        ),
    ]
